services:
  api:
    build: .
    container_name: lyftr-api
    ports:
      - "8000:8000"
    environment:
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      DATABASE_URL: sqlite:////data/app.db
    volumes:
      - app_data:/data
    restart: unless-stopped

volumes:
  app_data:
